logging:
  level:
    guru.springframework: debug
    org.hibernate.orm.jdbc.bind: trace
spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/restdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: restadmin
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: RestDB-Pool
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    properties:
      jakarta:
        persistence:
#          schema-generation:
#            scripts:
#              action: drop-and-create
#              create-source: metadata
#              drop-target: drop-and-create.sql
#              create-target: drop-and-create.sql
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true