logging:
  level:
    guru.springframework: debug
    org.zalando.logbook: trace
#    org.springframework.security: trace
spring:
  threads:
    virtual:
      enabled: true
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cache:
    cache-names:
      - beerCache
      - beerListCache
      - customerCache
      - customerListCache

server:
  port: 8081

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

