logging:
  level:
    guru.springframework: debug
#    org.springframework.security: trace
spring:
  threads:
    virtual:
      enabled: true
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

server:
  port: 8081